### ISSUE TITLE
better build instructions?

### ISSUE THREAD

**Issue by AskAlice** [section/section-cli#4]
i installed golang, and i get
```
go test ./... -v -timeout=45s -failfast
section.go:4:2: cannot find package "github.com/alecthomas/kong" in any of:
        /usr/lib/go-1.10/src/github.com/alecthomas/kong (from $GOROOT)
        /home/alice/go/src/github.com/alecthomas/kong (from $GOPATH)
section.go:5:2: cannot find package "github.com/section/section-cli/commands" in any of:
        /usr/lib/go-1.10/src/github.com/section/section-cli/commands (from $GOROOT)
        /home/alice/go/src/github.com/section/section-cli/commands (from $GOPATH)
commands/login.go:5:2: cannot find package "github.com/jdxcode/netrc" in any of:
        /usr/lib/go-1.10/src/github.com/jdxcode/netrc (from $GOROOT)
        /home/alice/go/src/github.com/jdxcode/netrc (from $GOPATH)
Makefile:16: recipe for target 'gotest' failed
make: *** [gotest] Error 1
```

**Comment by auxesis** [comment]
@AskAlice what version of Go are you running? 

`section-cli` uses [Go modules](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more) for managing dependencies. 

It looks like you don't have the dependencies cached locally. Go normally does this for you automatically. 

I've pushed a quick update (39d37b931514941dce203ad403c72ef023361d06) to the README stating you need to be running at least Go 1.14. 

If you are running Go ~1.14, can you please try running `go mod download`?
