### ISSUE TITLE
Add support for defaults accounts/apps/environments

### ISSUE THREAD

**Issue by auxesis** [section/section-cli#48]
Many commands require flags like `--account-id`, `--app-id`, and `--environment` to run.

This long form can be useful in scripts that run in CD pipelines, because they make it very explicit what's going on:

```
sectionctl deploy --account-id 2094 --app-id 7598 --environment production --directory commands/testdata/deploy/valid-nodejs-app/ --skip-delete
```

The flip side of this is that the local dev experience can be a clunky, because you need to specify the same arguments every time you run `sectionctl`:

```
sectionctl apps info --account-id 2094 --application-id 7598
```

This is particularly unergonomic for new users with a single account and a single app. The ideal experience should be running:

```
sectionctl apps info
```

and it runs successfully.

**Comment by AskAlice** [comment]
This has been implemented for deploy with https://github.com/section/sectionctl/pull/120 and was released in https://github.com/section/sectionctl/releases/tag/v1.11.1

I plan on making this a possibility for all commands later, using a kong resolver.
